version: '3.1'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: contribuintes
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postsenha
    ports:
      - "5433:5432"
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

  backend:
    build: .
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/contribuintes
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postsenha
    ports:
      - "8081:8080"
    networks:
      - app-network

  frontend:
    image: front-gestao-contribuintes:latest
    ports:
      - "80:80"
    networks:
      - app-network

volumes:
  postgres-data:

networks:
  app-network:
    driver: bridge